In [25]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

In [26]:
dataframe = pd.read_csv(r"StarterBook_Source.csv")
dataframe.head()

Clase  backers_count  Percent_Funded  Average_Donation   Gap_Days
0      1            182      136.858823             63.92  31.117928
1      1             79      142.608272            185.48  30.000000
2      1             35      105.000000             15.00  10.000000
3      1            150      103.900000             69.27  30.000000
4      1            284      122.991546            190.55  30.000000

In [27]:
dataframe.describe()

Clase  backers_count  Percent_Funded  Average_Donation  \
count  3715.000000    3715.000000    3.715000e+03       3715.000000   
mean      0.588156     121.646030    1.041131e+03         79.929612   
std       0.492233     654.595678    4.040332e+04        138.241661   
min       0.000000       0.000000    0.000000e+00          0.000000   
25%       0.000000       5.000000    3.931250e+00         27.145000   
50%       1.000000      28.000000    1.013333e+02         53.340000   
75%       1.000000      82.500000    1.169570e+02         91.220000   
max       1.000000   26457.000000    2.260300e+06       3000.000000   

          Gap_Days  
count  3715.000000  
mean     33.157411  
std      12.251457  
min       1.319537  
25%      29.958333  
50%      30.000000  
75%      35.000000  
max      90.000000

In [28]:
print(dataframe.groupby('Clase').size())

Clase
0    1530
1    2185
dtype: int64


In [35]:
X = np.array(dataframe.drop(['Clase'],1))
y = np.array(dataframe['Clase'])
X.shape

(3715, 4)

In [30]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [31]:
predictions = model.predict(X)

In [32]:
print(predictions)[0:5]

[1 1 1 ... 0 0 0]


TypeError: 'NoneType' object is not subscriptable

In [12]:
model.score(X,y)

0.9792732166890983

In [13]:
print(model)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [14]:
print(model.coef_)

[[-0.00123053  0.11884227 -0.00380031 -0.17324512]]


In [15]:
print(model.decision_function)

<bound method LinearClassifierMixin.decision_function of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)>


In [16]:
print(model.class_weight)

None


In [17]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [18]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(msg)

Logistic Regression: 0.993604 (0.005314)


In [19]:
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))

0.9784656796769852


In [20]:
print(confusion_matrix(Y_validation, predictions))

[[292  14]
 [  2 435]]


In [21]:
print(classification_report(Y_validation, predictions))

             precision    recall  f1-score   support

          0       0.99      0.95      0.97       306
          1       0.97      1.00      0.98       437

avg / total       0.98      0.98      0.98       743

